version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    volumes:
      - ./frontend/.env:/frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./backend/.env:/backend/.env
      - /home/connorslade/Documents:/backend/files
      - /home/connorslade/Programming/connorcode-writing:/backend/writing
      - ./.writing_cache:/backend/.writing_cache
