version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 8080:3000
    depends_on:
      - backend
    environment:
      - API_SERVER_ADDRESS=http://backend:8080
      - PUBLIC_FILE_ADDRESS=http://localhost:8081/api/files

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8081:8080
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/files:/backend/files
      - ./backend/writing:/backend/writing
      - ./backend/.writing_cache:/backend/.writing_cache
      - ./backend/.database:/backend/database
