FROM rust:1.78.0

WORKDIR /backend
COPY . .

# Install packages
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y sqlite3 libsqlite3-dev

# Build
RUN cargo install --path .

# Run server
EXPOSE 8080
CMD ["connorcode"]