name: Deploy backend

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: connorcode-backend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build `backend` image
        working-directory: backend
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main
